### ISSUE TITLE
mode selection not clear

### ISSUE THREAD

**Issue by wolverineks** [MrBIMC/SELinuxModeChanger#1]
The selection toggle is not clear as to which mode is selected.

This could cause some confusion and people might select one thinking they selected the other.

Perhaps a radio selector would clearly indicate which mode was selected, and which mode is deselected.

**Comment by MrBIMC** [comment]
WONT_FIX.

App consist of 2 buttons. Only one can be in the pressed state at a time. Obviously, the pressed one is selected. I have no idea how someone could not understand which one of these two buttons is selected.

**Comment by Anony1234mo** [comment]
dml
