### ISSUE TITLE
Unable to switch SElinux state

### ISSUE THREAD

**Issue by nirgranth** [MrBIMC/SELinuxModeChanger#12]
I am unable to switch states help pls
![Screenshot_20200707-012353](https://user-images.githubusercontent.com/48947296/86635456-b81a2980-bff0-11ea-8780-ac0c46ed206c.png)
![Screenshot_20200707-012401](https://user-images.githubusercontent.com/48947296/86635462-ba7c8380-bff0-11ea-9cd5-cae9c5613908.png)

**Comment by codedfiles** [comment]
Duplicate of #

**Comment by codedfiles** [comment]
Duplicate of #

**Comment by codedfiles** [comment]
app/src/main/java/com/mrbimc/selinux/MainActivity.kt

**Comment by ase12558** [comment]
> I am unable to switch states help pls ![Screenshot_20200707-012353](https://user-images.githubusercontent.com/48947296/86635456-b81a2980-bff0-11ea-8780-ac0c46ed206c.png) ![Screenshot_20200707-012401](https://user-images.githubusercontent.com/48947296/86635462-ba7c8380-bff0-11ea-9cd5-cae9c5613908.png)

**Comment by ase12558** [comment]
給

**Comment by ase12558** [comment]
> 給

**Comment by ase12558** [comment]
> I am unable to switch states help pls ![Screenshot_20200707-012353](https://user-images.githubusercontent.com/48947296/86635456-b81a2980-bff0-11ea-8780-ac0c46ed206c.png) ![Screenshot_20200707-012401](https://user-images.githubusercontent.com/48947296/86635462-ba7c8380-bff0-11ea-9cd5-cae9c5613908.png)

**Comment by nirgranth** [comment]
> > 給

what to give?
