### ISSUE TITLE
Not working on Android 5.0.1

### ISSUE THREAD

**Issue by lehitoskin** [MrBIMC/SELinuxModeChanger#6]
I have Android 5.0.1 on my Galaxy S4 and when I tap "Permissive", it still shows that SELinux mode is still "Enforcing" in the About Phone section. I tried restarting the phone, but then the program complains "App was unable to gain root access"

**Comment by MrBIMC** [comment]
Samsung firmwares are very tricky. Knoxx-related modifications reinforced a lot of android-provided security measures and thus it's much harder to switch SELinux context there. 

I tried the best I could to overcome it and so I added different options for the process of SELinux context switching to make wider amount of devices compatible. 

I just pushed v11 and I highly suggest you to try it out together with magisk-provided superuser.
